/**
 * Reads .github/workflows/ci.yml and writes docs/generated/ci-pipeline.md.
 * Run: node scripts/generate-ci-docs.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { parse } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const workflowPath = join(root, '.github/workflows/ci.yml');
const outDir = join(root, 'docs/generated');
const outPath = join(outDir, 'ci-pipeline.md');

function formatOn(on) {
  if (on == null) return '—';
  if (typeof on === 'string') return on;
  const lines = [];
  if (on.push) {
    lines.push(`- **push:** \`${JSON.stringify(on.push)}\``);
  }
  if (on.pull_request) {
    lines.push(`- **pull_request:** \`${JSON.stringify(on.pull_request)}\``);
  }
  if (on.workflow_dispatch) lines.push('- **workflow_dispatch**');
  return lines.length ? lines.join('\n') : `\`\`\`json\n${JSON.stringify(on, null, 2)}\n\`\`\``;
}

function stepTitle(step) {
  if (step.name) return step.name;
  if (step.uses) return `Action: ${step.uses}`;
  if (step.run) return 'Run';
  return 'Step';
}

function stepBody(step) {
  if (step.uses) {
    let s = `Uses \`${step.uses}\`.`;
    if (step.with && typeof step.with === 'object') {
      s += '\n\n| Input | Value |\n| --- | --- |\n';
      for (const [k, v] of Object.entries(step.with)) {
        s += `| \`${k}\` | \`${String(v).replace(/\|/g, '\\|')}\` |\n`;
      }
    }
    return s;
  }
  if (step.run) {
    const fence = '```';
    return `${fence}text\n${step.run.trimEnd()}\n${fence}`;
  }
  return '—';
}

const raw = readFileSync(workflowPath, 'utf8');
const doc = parse(raw);

let md =
  '<!-- DO NOT EDIT BY HAND. Generated by `node scripts/generate-ci-docs.mjs`. -->\n\n';
md += `# CI pipeline (generated)\n\n`;
md += `Regenerate after editing [\`.github/workflows/ci.yml\`](../.github/workflows/ci.yml):\n\n`;
md += `\`\`\`bash\nnpm run generate-ci-docs\n\`\`\`\n\n`;
md += `## Triggers\n\n`;
md += `${formatOn(doc.on)}\n\n`;

const jobs = doc.jobs || {};
for (const [jobName, job] of Object.entries(jobs)) {
  md += `## Job: \`${jobName}\`\n\n`;
  if (job['runs-on']) md += `- **runs-on:** \`${job['runs-on']}\`\n`;
  if (job.needs != null) {
    const n = Array.isArray(job.needs) ? job.needs.join('`, `') : job.needs;
    md += `- **needs:** \`${n}\`\n`;
  }
  if (job.if != null) md += `- **if:** \`${String(job.if).replace(/`/g, "'")}\`\n`;
  md += `\n`;

  let i = 1;
  for (const step of job.steps || []) {
    md += `### ${i}. ${stepTitle(step)}\n\n`;
    md += `${stepBody(step)}\n\n`;
    i += 1;
  }
}

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, md, 'utf8');
console.log(`Wrote ${outPath}`);
